package Presentacion;

//import Util.FondoPanel;
import Beans.Cliente;
import Beans.Factura;
import Logica.ClienteLogica;
import Logica.FacturaLogica;
import java.net.URL;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DERICK ALEXIS
 */
public class Dashboard extends javax.swing.JFrame {
    
    private LoginForm v1; // Referencia al LoginForm
    private final RegistrarClienteFrame v3 = new RegistrarClienteFrame();
    private final PagosFrame v4 = new PagosFrame();
    private final MedidorFrame v5 = new MedidorFrame();
    private final DeudoresFrame v6 = new DeudoresFrame();
    private final HistorialFrame v7 = new HistorialFrame();

    /**
     * Constructor del Dashboard
     */
    public Dashboard() {
    initComponents();
    this.setLocationRelativeTo(null); 
    cargarDatosEstadisticos(); // Cargar datos reales en labels y tablas
}

private void cargarDatosEstadisticos() {
    ClienteLogica clienteLogica = new ClienteLogica();
    FacturaLogica facturaLogica = new FacturaLogica();
    
    int totalClientes = clienteLogica.contarClientes();
    int facturasPendientes = facturaLogica.contarFacturasPorEstado("Pendiente");
    int facturasParciales = facturaLogica.contarFacturasPorEstado("Parcial");
    int facturasPagadas = facturaLogica.contarFacturasPorEstado("Pagado");
    
    // Mostrar valores en las etiquetas
    jLabelValorClientes.setText(String.valueOf(totalClientes));
    jLabelValorPendientes.setText(String.valueOf(facturasPendientes));
    jLabelValorParciales.setText(String.valueOf(facturasParciales));
    jLabelValorPagadas.setText(String.valueOf(facturasPagadas));
    
    // Cargar las tablas
    cargarTablaClientes(clienteLogica.obtenerTodosLosClientes());
    cargarTablaFacturasEstado("Pendiente", jTableValorPendientes);
    cargarTablaFacturasEstado("Parcial", jTableValorParciales);
    cargarTablaFacturasEstado("Pagado", jTableValorPagadas);
}

// Carga la tabla de clientes con el nombre del cliente (puedes agregar más columnas según necesites)
private void cargarTablaClientes(List<Cliente> clientes) {
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
        new Object[]{"Cliente"}, 0
    );
    for (Cliente c : clientes) {
        modelo.addRow(new Object[]{c.getNombre()});
    }
    jTableValorClientes.setModel(modelo);
}

// Carga las tablas de facturas (pendientes, parciales, pagadas) con cliente, monto y estado
private void cargarTablaFacturasEstado(String estado, javax.swing.JTable tabla) {
    FacturaLogica facturaLogica = new FacturaLogica();
    ClienteLogica clienteLogica = new ClienteLogica();
    
    List<Factura> facturas = facturaLogica.obtenerFacturasPorEstado(estado);
    
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
        new Object[]{"Cliente", "Monto", "Estado"}, 0
    );
    
    for (Factura f : facturas) {
        // Obtener nombre del cliente
        String nombreCliente = "Desconocido";
        Cliente cli = clienteLogica.obtenerClientePorId(f.getIdUsuario());
        if (cli != null) {
            nombreCliente = cli.getNombre();
        }
        
        modelo.addRow(new Object[]{nombreCliente, f.getMontoPendiente(), f.getEstadoPago()});
    }
    
    tabla.setModel(modelo);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnBotonRegistrarV3 = new javax.swing.JButton();
        btnPagosV4 = new javax.swing.JButton();
        btnMedidoresV5 = new javax.swing.JButton();
        btnDeudoresV6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnHistorialV7 = new javax.swing.JButton();
        jPanel_listaDatos1 = new javax.swing.JPanel();
        jLabelTituloClientes = new javax.swing.JLabel();
        jLabelValorClientes = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableValorClientes = new javax.swing.JTable();
        jPanel_listaDatos2 = new javax.swing.JPanel();
        jLabelTituloPendientes = new javax.swing.JLabel();
        jLabelValorPendientes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableValorPendientes = new javax.swing.JTable();
        jPanel_listaDatos3 = new javax.swing.JPanel();
        jLabelTituloParciales = new javax.swing.JLabel();
        jLabelValorParciales = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableValorParciales = new javax.swing.JTable();
        jPanel_listaDatos4 = new javax.swing.JPanel();
        jLabelTituloPagadas = new javax.swing.JLabel();
        jLabelValorPagadas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableValorPagadas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnBotonRegistrarV3.setBackground(new java.awt.Color(0, 153, 204));
        btnBotonRegistrarV3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnBotonRegistrarV3.setForeground(new java.awt.Color(255, 255, 255));
        btnBotonRegistrarV3.setText("Registrar usuario");
        btnBotonRegistrarV3.setBorder(null);
        btnBotonRegistrarV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotonRegistrarV3ActionPerformed(evt);
            }
        });

        btnPagosV4.setBackground(new java.awt.Color(0, 153, 204));
        btnPagosV4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnPagosV4.setForeground(new java.awt.Color(255, 255, 255));
        btnPagosV4.setText("Realizar pagos");
        btnPagosV4.setBorder(null);
        btnPagosV4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagosV4ActionPerformed(evt);
            }
        });

        btnMedidoresV5.setBackground(new java.awt.Color(0, 102, 153));
        btnMedidoresV5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnMedidoresV5.setForeground(new java.awt.Color(255, 255, 255));
        btnMedidoresV5.setText("Ingreso de consumo medidores");
        btnMedidoresV5.setBorder(null);
        btnMedidoresV5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedidoresV5ActionPerformed(evt);
            }
        });

        btnDeudoresV6.setBackground(new java.awt.Color(0, 153, 204));
        btnDeudoresV6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnDeudoresV6.setForeground(new java.awt.Color(255, 255, 255));
        btnDeudoresV6.setText("Visualizar deudores");
        btnDeudoresV6.setBorder(null);
        btnDeudoresV6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeudoresV6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnBotonRegistrarV3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPagosV4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMedidoresV5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeudoresV6, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBotonRegistrarV3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagosV4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedidoresV5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeudoresV6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 90));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FactuTrack");

        btnRegresar.setBackground(new java.awt.Color(255, 102, 102));
        btnRegresar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Cerrar sesión");
        btnRegresar.setBorder(null);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bienvenido");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Admin");

        btnHistorialV7.setBackground(new java.awt.Color(0, 153, 204));
        btnHistorialV7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnHistorialV7.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorialV7.setText("Historial de consumo de usuario");
        btnHistorialV7.setBorder(null);
        btnHistorialV7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialV7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnHistorialV7, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 741, Short.MAX_VALUE)
                                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnHistorialV7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 220));

        jPanel_listaDatos1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_listaDatos1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTituloClientes.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelTituloClientes.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTituloClientes.setText("Total de clientes registrados");

        jLabelValorClientes.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        jLabelValorClientes.setForeground(new java.awt.Color(0, 153, 255));
        jLabelValorClientes.setText("jLabel9");

        jTableValorClientes.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTableValorClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableValorClientes);

        javax.swing.GroupLayout jPanel_listaDatos1Layout = new javax.swing.GroupLayout(jPanel_listaDatos1);
        jPanel_listaDatos1.setLayout(jPanel_listaDatos1Layout);
        jPanel_listaDatos1Layout.setHorizontalGroup(
            jPanel_listaDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_listaDatos1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel_listaDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelValorClientes)
                    .addComponent(jLabelTituloClientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel_listaDatos1Layout.setVerticalGroup(
            jPanel_listaDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_listaDatos1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel_listaDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_listaDatos1Layout.createSequentialGroup()
                        .addComponent(jLabelTituloClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelValorClientes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel_listaDatos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 570, 150));

        jPanel_listaDatos2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_listaDatos2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTituloPendientes.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelTituloPendientes.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTituloPendientes.setText("Total de facturas pendientes");

        jLabelValorPendientes.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        jLabelValorPendientes.setForeground(new java.awt.Color(0, 153, 255));
        jLabelValorPendientes.setText("jLabel10");

        jTableValorPendientes.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTableValorPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableValorPendientes);

        javax.swing.GroupLayout jPanel_listaDatos2Layout = new javax.swing.GroupLayout(jPanel_listaDatos2);
        jPanel_listaDatos2.setLayout(jPanel_listaDatos2Layout);
        jPanel_listaDatos2Layout.setHorizontalGroup(
            jPanel_listaDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_listaDatos2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel_listaDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelValorPendientes)
                    .addComponent(jLabelTituloPendientes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel_listaDatos2Layout.setVerticalGroup(
            jPanel_listaDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_listaDatos2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel_listaDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_listaDatos2Layout.createSequentialGroup()
                        .addComponent(jLabelTituloPendientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelValorPendientes)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel_listaDatos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 510, 150));

        jPanel_listaDatos3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_listaDatos3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTituloParciales.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelTituloParciales.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTituloParciales.setText("Total de facturas parciales");

        jLabelValorParciales.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        jLabelValorParciales.setForeground(new java.awt.Color(0, 153, 255));
        jLabelValorParciales.setText("jLabel11");

        jTableValorParciales.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTableValorParciales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableValorParciales);

        javax.swing.GroupLayout jPanel_listaDatos3Layout = new javax.swing.GroupLayout(jPanel_listaDatos3);
        jPanel_listaDatos3.setLayout(jPanel_listaDatos3Layout);
        jPanel_listaDatos3Layout.setHorizontalGroup(
            jPanel_listaDatos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_listaDatos3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_listaDatos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelValorParciales)
                    .addComponent(jLabelTituloParciales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel_listaDatos3Layout.setVerticalGroup(
            jPanel_listaDatos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_listaDatos3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel_listaDatos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_listaDatos3Layout.createSequentialGroup()
                        .addComponent(jLabelTituloParciales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelValorParciales)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel_listaDatos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 570, 160));

        jPanel_listaDatos4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_listaDatos4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTituloPagadas.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabelTituloPagadas.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTituloPagadas.setText("Total de facturas pagadas");

        jLabelValorPagadas.setFont(new java.awt.Font("Roboto", 0, 48)); // NOI18N
        jLabelValorPagadas.setForeground(new java.awt.Color(0, 153, 255));
        jLabelValorPagadas.setText("jLabel12");

        jTableValorPagadas.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTableValorPagadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableValorPagadas);

        javax.swing.GroupLayout jPanel_listaDatos4Layout = new javax.swing.GroupLayout(jPanel_listaDatos4);
        jPanel_listaDatos4.setLayout(jPanel_listaDatos4Layout);
        jPanel_listaDatos4Layout.setHorizontalGroup(
            jPanel_listaDatos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_listaDatos4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel_listaDatos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelValorPagadas)
                    .addComponent(jLabelTituloPagadas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel_listaDatos4Layout.setVerticalGroup(
            jPanel_listaDatos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_listaDatos4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel_listaDatos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel_listaDatos4Layout.createSequentialGroup()
                        .addComponent(jLabelTituloPagadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelValorPagadas)
                        .addGap(0, 47, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel_listaDatos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 510, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método para establecer la referencia al LoginForm
     *
     * @param v1 Referencia al LoginForm
     */
    public void setV1(LoginForm v1) {
        if (v1 != null) {
            this.v1 = v1;
        } else {
            System.err.println("Referencia a LoginForm es nula.");
        }
    }


    /**
     * Método para cambiar de ventana.
     *
     * @param frame Frame que se va a mostrar.
     */
    private void cambiarVentana(javax.swing.JFrame frame) {
        try {
            frame.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al abrir la ventana: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    /**
     * Acción del botón "Cerrar sesión"
     */
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        if (v1 != null) {
            v1.limpiarCampos(); // Limpia los campos del LoginForm
            v1.setVisible(true); // Mostrar LoginForm
            this.setVisible(false); // Ocultar Dashboard
        } else {
            JOptionPane.showMessageDialog(this, "Error: LoginForm no está configurado.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * Acción del botón "Registrar usuario"
     */
    private void btnBotonRegistrarV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotonRegistrarV3ActionPerformed
        v3.setV2(this);
        cambiarVentana(v3);
    }//GEN-LAST:event_btnBotonRegistrarV3ActionPerformed

    /**
     * Acción del botón "Realizar pagos"
     */
    private void btnPagosV4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagosV4ActionPerformed
        v4.setV2(this);
        cambiarVentana(v4);
    }//GEN-LAST:event_btnPagosV4ActionPerformed

    /**
     * Acción del botón "Visualizar deudores"
     */
    private void btnDeudoresV6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeudoresV6ActionPerformed
        v6.setV2(this);
        cambiarVentana(v6);
    }//GEN-LAST:event_btnDeudoresV6ActionPerformed

    /**
     * Acción del botón "Ingreso de consumo medidores"
     */
    private void btnMedidoresV5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedidoresV5ActionPerformed
        v5.setV2(this);
        cambiarVentana(v5);
    }//GEN-LAST:event_btnMedidoresV5ActionPerformed

    /**
     * Acción del botón "Historial de consumo de usuario"
     */
    private void btnHistorialV7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialV7ActionPerformed
        v7.setV2(this);
        cambiarVentana(v7);
    }//GEN-LAST:event_btnHistorialV7ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBotonRegistrarV3;
    private javax.swing.JButton btnDeudoresV6;
    private javax.swing.JButton btnHistorialV7;
    private javax.swing.JButton btnMedidoresV5;
    private javax.swing.JButton btnPagosV4;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelTituloClientes;
    private javax.swing.JLabel jLabelTituloPagadas;
    private javax.swing.JLabel jLabelTituloParciales;
    private javax.swing.JLabel jLabelTituloPendientes;
    private javax.swing.JLabel jLabelValorClientes;
    private javax.swing.JLabel jLabelValorPagadas;
    private javax.swing.JLabel jLabelValorParciales;
    private javax.swing.JLabel jLabelValorPendientes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_listaDatos1;
    private javax.swing.JPanel jPanel_listaDatos2;
    private javax.swing.JPanel jPanel_listaDatos3;
    private javax.swing.JPanel jPanel_listaDatos4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableValorClientes;
    private javax.swing.JTable jTableValorPagadas;
    private javax.swing.JTable jTableValorParciales;
    private javax.swing.JTable jTableValorPendientes;
    // End of variables declaration//GEN-END:variables
}
