/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Logica.ClienteLogica;
import Logica.FacturaLogica;
import Beans.Cliente;
import Beans.Factura;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
/**
 *
 * @author DERICK ALEXIS
 */
public class DeudoresFrame extends javax.swing.JFrame {

    private Dashboard v2; // Referencia al Dashboard

    public DeudoresFrame() {
        initComponents();
        inicializarTabla(); // Configurar encabezados de tabla
        this.setLocationRelativeTo(this); // Centrar la ventana
        cargarDeudores(); // Cargar deudores al inicio
    }

    /**
     * Configura los encabezados de la tabla.
     */
    private void inicializarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
            new String[]{"ID Usuario", "DNI", "Nombre", "Monto Pendiente", "Estado Servicio"}, 0
        );
        jTable_deudores.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_deudores = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton_optionSuspendido = new javax.swing.JRadioButton();
        jRadioButton_optionActivo = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_buscar_id_dni = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton_buscar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton_atras = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lista de deudores");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jTable_deudores.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTable_deudores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_deudores);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 620, 400));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Modificar estado de servicio:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 185, -1));

        buttonGroup1.add(jRadioButton_optionSuspendido);
        jRadioButton_optionSuspendido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jRadioButton_optionSuspendido.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_optionSuspendido.setText("Suspender");
        jPanel1.add(jRadioButton_optionSuspendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));
        jRadioButton_optionSuspendido.getAccessibleContext().setAccessibleDescription("");

        buttonGroup1.add(jRadioButton_optionActivo);
        jRadioButton_optionActivo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jRadioButton_optionActivo.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton_optionActivo.setText("Activo");
        jPanel1.add(jRadioButton_optionActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Buscar por idUsuario o DNI:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, 35));

        jTextField_buscar_id_dni.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextField_buscar_id_dni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_buscar_id_dniActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField_buscar_id_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 262, 35));

        jLabel5.setText("Respuesta Busqueda");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 260, -1));

        jButton_buscar.setBackground(new java.awt.Color(0, 153, 204));
        jButton_buscar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton_buscar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_buscar.setText("Buscar");
        jButton_buscar.setBorder(null);
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });
        jPanel2.add(jButton_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 89, 35));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));

        jLabel4.setBackground(new java.awt.Color(153, 153, 153));
        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 204, 255));
        jLabel4.setText("Dashboard >  Lista de deudores");

        jButton_atras.setBackground(new java.awt.Color(255, 102, 102));
        jButton_atras.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton_atras.setForeground(new java.awt.Color(255, 255, 255));
        jButton_atras.setText("Atras");
        jButton_atras.setBorder(null);
        jButton_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(431, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 180));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 740, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Carga los datos de los deudores en la tabla.
     */
    private void cargarDeudores() {
        DefaultTableModel modelo = (DefaultTableModel) jTable_deudores.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        ClienteLogica clienteLogica = new ClienteLogica();
        FacturaLogica facturaLogica = new FacturaLogica();

        List<Cliente> clientes = clienteLogica.obtenerClientes();

        for (Cliente cliente : clientes) {
            List<Factura> facturasPendientes = facturaLogica.obtenerFacturasPendientesPorUsuario(cliente.getIdUsuario());

            if (!facturasPendientes.isEmpty()) {
                double montoPendiente = facturasPendientes.stream()
                    .mapToDouble(Factura::getMonto)
                    .sum();

                modelo.addRow(new Object[]{
                    cliente.getIdUsuario(),
                    cliente.getDni(),
                    cliente.getNombre(),
                    montoPendiente,
                    cliente.getEstadoServicio()
                });
            }
        }
    }

    public void setV2(Dashboard v2) {
        this.v2 = v2;
    }

    /**
     * Modifica el estado de servicio de un cliente seleccionado.
     */
    private void modificarEstadoServicio() {
        int filaSeleccionada = jTable_deudores.getSelectedRow();

        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idUsuario = (int) jTable_deudores.getValueAt(filaSeleccionada, 0);
        String nuevoEstado = jRadioButton_optionActivo.isSelected() ? "Activo" : "Suspendido";

        ClienteLogica clienteLogica = new ClienteLogica();
        Cliente cliente = clienteLogica.obtenerClientePorId(idUsuario);
        cliente.setEstadoServicio(nuevoEstado);

        if (clienteLogica.actualizarCliente(cliente)) {
            JOptionPane.showMessageDialog(this, "Estado de servicio actualizado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            cargarDeudores(); // Recargar tabla
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar el estado de servicio.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Realiza la búsqueda de un cliente por ID o DNI.
     */
    private void buscarCliente() {
        String idODni = jTextField_buscar_id_dni.getText().trim();

        if (idODni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID o DNI para buscar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ClienteLogica clienteLogica = new ClienteLogica();
        Cliente cliente = clienteLogica.obtenerClientePorDniOId(idODni);

        if (cliente == null) {
            JOptionPane.showMessageDialog(this, "No se encontró un usuario con el ID o DNI proporcionado.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) jTable_deudores.getModel();
            modelo.setRowCount(0);

            FacturaLogica facturaLogica = new FacturaLogica();
            List<Factura> facturasPendientes = facturaLogica.obtenerFacturasPendientesPorUsuario(cliente.getIdUsuario());

            if (!facturasPendientes.isEmpty()) {
                double montoPendiente = facturasPendientes.stream()
                    .mapToDouble(Factura::getMonto)
                    .sum();

                modelo.addRow(new Object[]{
                    cliente.getIdUsuario(),
                    cliente.getDni(),
                    cliente.getNombre(),
                    montoPendiente,
                    cliente.getEstadoServicio()
                });
            }
        }
    }
    private void jButton_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atrasActionPerformed
        // TODO add your handling code here:
        v2.setVisible(true); // Nos regresa atras a la pantalla V2
        this.setVisible(false);
    }//GEN-LAST:event_jButton_atrasActionPerformed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        // TODO add your handling code here:
        buscarCliente();
    }//GEN-LAST:event_jButton_buscarActionPerformed

    private void jTextField_buscar_id_dniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_buscar_id_dniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_buscar_id_dniActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_atras;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton_optionActivo;
    private javax.swing.JRadioButton jRadioButton_optionSuspendido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_deudores;
    private javax.swing.JTextField jTextField_buscar_id_dni;
    // End of variables declaration//GEN-END:variables
}
