/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Logica.ClienteLogica;
import Logica.ConsumoLogica;
import Logica.FacturaLogica;
import modelo.Cliente;
import modelo.Consumo;
import modelo.Factura;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
/**
 *
 * @author DERICK ALEXIS
 */
public class HistorialFrame extends javax.swing.JFrame {

    private Dashboard v2;

    public HistorialFrame() {
        initComponents();
        this.setLocationRelativeTo(this);
        configurarEncabezadosTabla(); // Configurar encabezados
        cargarHistorialCompleto(); // Cargar todo el historial por defecto
    }

    public void setV2(Dashboard v2) {
        this.v2 = v2;
    }

    /**
     * Configura los encabezados de la tabla.
     */
    private void configurarEncabezadosTabla() {
        DefaultTableModel modelo = (DefaultTableModel) jTable_historial.getModel();
        modelo.setColumnIdentifiers(new String[]{
                "Nombre Cliente", "Fecha Consumo", "Consumo (m³)", "Monto Factura (S/)", "Estado Pago", "Fecha Vencimiento", "Status"
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_buscar_id_dni = new javax.swing.JTextField();
        jButton_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_historial = new javax.swing.JTable();
        jButton_atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel2.setText("FactuTrack");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Historial de consumo de usuario");

        jLabel1.setText("Buscar por idusuario o DNI:");

        jButton_buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_buscar.setText("Buscar");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        jTable_historial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_historial);

        jButton_atras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_atras.setText("Atras");
        jButton_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField_buscar_id_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(94, 94, 94)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_buscar_id_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton_atras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Carga todo el historial de todos los clientes al iniciar.
     */
    private void cargarHistorialCompleto() {
        DefaultTableModel modelo = (DefaultTableModel) jTable_historial.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        ClienteLogica clienteLogica = new ClienteLogica();
        ConsumoLogica consumoLogica = new ConsumoLogica();
        FacturaLogica facturaLogica = new FacturaLogica();

        List<Cliente> clientes = clienteLogica.obtenerClientes();

        for (Cliente cliente : clientes) {
            int idUsuario = cliente.getIdUsuario();
            List<Consumo> consumos = consumoLogica.obtenerConsumosPorUsuario(idUsuario);
            List<Factura> facturas = facturaLogica.obtenerFacturasPorUsuario(idUsuario);

            for (int i = 0; i < consumos.size(); i++) {
                Consumo consumo = consumos.get(i);
                Factura factura = facturas.get(i); // Se asume una factura por cada consumo

                modelo.addRow(new Object[]{
                        cliente.getNombre(),
                        consumo.getMes(),
                        consumo.getConsumoMensual(),
                        factura.getMonto(),
                        factura.getEstadoPago(),
                        factura.getFechaVencimiento(),
                        factura.getStatus()
                });
            }
        }
    }

    /**
     * Carga el historial de un cliente específico.
     *
     * @param idUsuario ID del usuario.
     */
    private void cargarHistorialPorCliente(int idUsuario) {
        DefaultTableModel modelo = (DefaultTableModel) jTable_historial.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        ClienteLogica clienteLogica = new ClienteLogica();
        ConsumoLogica consumoLogica = new ConsumoLogica();
        FacturaLogica facturaLogica = new FacturaLogica();

        Cliente cliente = clienteLogica.obtenerClientePorId(idUsuario);
        if (cliente != null) {
            List<Consumo> consumos = consumoLogica.obtenerConsumosPorUsuario(idUsuario);
            List<Factura> facturas = facturaLogica.obtenerFacturasPorUsuario(idUsuario);

            for (int i = 0; i < consumos.size(); i++) {
                Consumo consumo = consumos.get(i);
                Factura factura = facturas.get(i); // Se asume una factura por cada consumo

                modelo.addRow(new Object[]{
                        cliente.getNombre(),
                        consumo.getMes(),
                        consumo.getConsumoMensual(),
                        factura.getMonto(),
                        factura.getEstadoPago(),
                        factura.getFechaVencimiento(),
                        factura.getStatus()
                });
            }
        }
    }
    
    private void jButton_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atrasActionPerformed
        // TODO add your handling code here:
        v2.setVisible(true); // Nos regresa atras a la pantalla V2
        this.setVisible(false);
    }//GEN-LAST:event_jButton_atrasActionPerformed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        // TODO add your handling code here:
        String idODni = jTextField_buscar_id_dni.getText().trim();

        if (idODni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID o DNI para buscar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            cargarHistorialCompleto(); // Cargar todo si no hay búsqueda
            return;
        }

        ClienteLogica clienteLogica = new ClienteLogica();
        int idUsuario = clienteLogica.obtenerIdUsuarioPorDniOId(idODni);

        if (idUsuario == -1) {
            JOptionPane.showMessageDialog(this, "No se encontró un usuario con el ID o DNI proporcionado.", "Error", JOptionPane.ERROR_MESSAGE);
            DefaultTableModel modelo = (DefaultTableModel) jTable_historial.getModel();
            modelo.setRowCount(0); // Limpiar tabla
        } else {
            cargarHistorialPorCliente(idUsuario);
        }
    }//GEN-LAST:event_jButton_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_atras;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_historial;
    private javax.swing.JTextField jTextField_buscar_id_dni;
    // End of variables declaration//GEN-END:variables
}
