/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Logica.ClienteLogica;
import Logica.ConsumoLogica;
import Logica.FacturaLogica;
import Beans.Consumo;
import Beans.Factura;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
/**
 *
 * @author DERICK ALEXIS
 */
public class MedidorFrame extends javax.swing.JFrame {

    private Dashboard v2; // Referencia al Dashboard
    private FacturaLogica facturaLogica;
    private ConsumoLogica consumoLogica;
    private ClienteLogica clienteLogica;

    public MedidorFrame() {
        initComponents();
        inicializarTabla();
        this.setLocationRelativeTo(this);

        facturaLogica = new FacturaLogica();
        consumoLogica = new ConsumoLogica();
        clienteLogica = new ClienteLogica();

        // Cargar todos los consumos al iniciar
        cargarDatosTabla(-1);
    }


    /**
     * Inicializa la tabla con los encabezados correctos.
     */
    private void inicializarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
            new String[]{"Fecha Consumo", "Consumo Mensual (m³)", "Monto Factura (S/)", "Estado Pago"}, 0
        );
        jTable_consumo_factura_medidor.setModel(modelo);
    }

    /**
     * Carga los datos de consumo y facturas en la tabla para un usuario.
     */
    private void cargarDatosTabla(int idUsuario) {
        DefaultTableModel modelo = (DefaultTableModel) jTable_consumo_factura_medidor.getModel();
        modelo.setRowCount(0);

        List<Consumo> consumos;
        List<Factura> facturas;

        if (idUsuario == -1) {
            // Cargar todos los consumos y facturas
            consumos = consumoLogica.obtenerTodosLosConsumos();
            facturas = facturaLogica.obtenerTodasLasFacturas();
        } else {
            // Cargar consumos y facturas para un usuario específico
            consumos = consumoLogica.obtenerConsumosPorUsuario(idUsuario);
            facturas = facturaLogica.obtenerFacturasPorUsuario(idUsuario);
        }

        for (Consumo consumo : consumos) {
            Factura facturaRelacionada = null;

            // Buscar la factura relacionada
            for (Factura factura : facturas) {
                if (factura.getFechaEmision().startsWith(consumo.getMes())) {
                    facturaRelacionada = factura;
                    break;
                }
            }

            modelo.addRow(new Object[]{
                consumo.getMes(),
                consumo.getConsumoMensual(),
                facturaRelacionada != null ? facturaRelacionada.getMonto() : "No Facturado",
                facturaRelacionada != null ? facturaRelacionada.getEstadoPago() : "N/A"
            });
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void setV2(Dashboard v2){
        this.v2 = v2;
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_buscar_id_dni = new javax.swing.JTextField();
        jLabel_resultado_nombreCliente = new javax.swing.JLabel();
        jButton_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_consumo_factura_medidor = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton_atras = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton_registrar_consumo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField_consumo_mes = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser_fecha_consumo = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setText("Buscar por idusuario o DNI:");

        jLabel_resultado_nombreCliente.setText("Respuesta Busqueda");

        jButton_buscar.setBackground(new java.awt.Color(0, 153, 204));
        jButton_buscar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton_buscar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_buscar.setText("Buscar");
        jButton_buscar.setBorder(null);
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel_resultado_nombreCliente)))
                .addContainerGap(283, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(173, 173, 173)
                    .addComponent(jTextField_buscar_id_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_resultado_nombreCliente)
                .addGap(15, 15, 15))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jTextField_buscar_id_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(26, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 570, 80));

        jTable_consumo_factura_medidor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_consumo_factura_medidor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 756, 246));

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_atras.setBackground(new java.awt.Color(255, 102, 102));
        jButton_atras.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton_atras.setForeground(new java.awt.Color(255, 255, 255));
        jButton_atras.setText("Atras");
        jButton_atras.setBorder(null);
        jButton_atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atrasActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 40));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ingreso consumo medidores");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 204, 255));
        jLabel10.setText("Dashboard >  Ingreso consumo medidores");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 120));

        jButton_registrar_consumo.setBackground(new java.awt.Color(102, 153, 255));
        jButton_registrar_consumo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton_registrar_consumo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_registrar_consumo.setText("Registrar Consumo");
        jButton_registrar_consumo.setBorder(null);
        jButton_registrar_consumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registrar_consumoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_registrar_consumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 180, 37));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setText("Ingresar consumo del mes (metro cubico) :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));
        getContentPane().add(jTextField_consumo_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 250, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel4.setText("Escriba la fecha del consumo (opcional)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));
        getContentPane().add(jDateChooser_fecha_consumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 130, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton_atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atrasActionPerformed
        // TODO add your handling code here:
        v2.setVisible(true); // Nos regresa atras a la pantalla V2
        this.setVisible(false);
    }//GEN-LAST:event_jButton_atrasActionPerformed

    private void jButton_registrar_consumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registrar_consumoActionPerformed
        // TODO add your handling code here:
        String idODni = jTextField_buscar_id_dni.getText().trim();
        String consumoTexto = jTextField_consumo_mes.getText().trim();
        Date fechaSeleccionada = jDateChooser_fecha_consumo.getDate();

        if (idODni.isEmpty() || consumoTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete los campos obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            double consumoMensual = Double.parseDouble(consumoTexto);
            if (consumoMensual <= 0) {
                JOptionPane.showMessageDialog(this, "El consumo debe ser mayor a 0.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int idUsuario = clienteLogica.obtenerIdUsuarioPorDniOId(idODni);
            if (idUsuario == -1) {
                JOptionPane.showMessageDialog(this, "No se encontró un usuario con el ID o DNI proporcionado.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            System.out.println("ID Usuario: " + idUsuario + ", Consumo Mensual: " + consumoMensual); // Depuración

            Consumo consumo = new Consumo();
            consumo.setIdUsuario(idUsuario);
            String fechaConsumo = (fechaSeleccionada != null)
                    ? new SimpleDateFormat("yyyy-MM").format(fechaSeleccionada)
                    : new SimpleDateFormat("yyyy-MM").format(new Date());
            consumo.setMes(fechaConsumo);
            consumo.setConsumoMensual(consumoMensual);

            boolean resultadoConsumo = consumoLogica.registrarConsumo(consumo);

            if (resultadoConsumo) {
                String resultadoFactura = facturaLogica.registrarConsumoYFactura(idUsuario, consumoMensual, fechaSeleccionada);

                if ("success".equals(resultadoFactura)) {
                    JOptionPane.showMessageDialog(this, "Consumo y factura registrados con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    cargarDatosTabla(-1);
                } else {
                    JOptionPane.showMessageDialog(this, "Error al generar la factura: " + resultadoFactura, "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error al registrar el consumo.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un valor numérico válido para el consumo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_registrar_consumoActionPerformed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        // Obtener el valor ingresado por el usuario
        String idODni = jTextField_buscar_id_dni.getText().trim();

        if (idODni.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID o DNI para buscar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idUsuario = clienteLogica.obtenerIdUsuarioPorDniOId(idODni);
        if (idUsuario == -1) {
            jLabel_resultado_nombreCliente.setText("No se encontró un usuario con el ID o DNI proporcionado.");
            cargarDatosTabla(-1); // Limpiar tabla en caso de búsqueda fallida
        } else {
            jLabel_resultado_nombreCliente.setText("Cliente encontrado: " + clienteLogica.obtenerNombrePorId(idUsuario));
            cargarDatosTabla(idUsuario);
        }
    }//GEN-LAST:event_jButton_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_atras;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_registrar_consumo;
    private com.toedter.calendar.JDateChooser jDateChooser_fecha_consumo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_resultado_nombreCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_consumo_factura_medidor;
    private javax.swing.JTextField jTextField_buscar_id_dni;
    private javax.swing.JTextField jTextField_consumo_mes;
    // End of variables declaration//GEN-END:variables
}
