/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Logica.ClienteLogica;
import modelo.Cliente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
/**
 *
 * @author DERICK ALEXIS
 */
public class RegistrarClienteFrame extends javax.swing.JFrame {
    
    private Dashboard v2; // Referencia al Dashboard
    private DefaultTableModel modeloTabla; // Modelo para la tabla

    public RegistrarClienteFrame() {
        initComponents();
        this.setLocationRelativeTo(this); // Centrar ventana
        inicializarModeloTabla(); // Configurar modelo de la tabla
        cargarClientesEnTabla(); // Cargar datos al inicio
    }

    /**
     * Configura la referencia al Dashboard.
     *
     * @param v2 Referencia al Dashboard.
     */
    public void setV2(Dashboard v2) {
        this.v2 = v2;
    }

    /**
     * Limpia los campos del formulario.
     */
    private void limpiarCampos() {
        jTextField_nombre.setText("");
        jTextField_dni.setText("");
        jTextField_direccion.setText("");
        jTextField_telefono.setText("");
        jDateChooser_fechaInstalacion.setDate(null);
        jRadioButton_medidor_option_si.setSelected(false);
        jRadioButton_medidor_option_no.setSelected(false);
        jRadioButton_estadoServicio_option_activo.setSelected(false);
        jRadioButton_estadoServicio_option_suspendido.setSelected(false);
    }

    /**
     * Captura la fecha del `JDateChooser` y la convierte a `String`.
     *
     * @return Fecha en formato `yyyy-MM-dd` o `null` si no está seleccionada.
     */
    private String obtenerFechaInstalacion() {
        Date fecha = jDateChooser_fechaInstalacion.getDate();
        if (fecha != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            return sdf.format(fecha);
        }
        return null;
    }

    /**
     * Configura el modelo para la tabla de clientes.
     */
    private void inicializarModeloTabla() {
        modeloTabla = new DefaultTableModel(
                new String[]{"ID", "Nombre", "DNI", "Dirección", "Teléfono", "Medidor", "Estado", "Fecha Instalación"},
                0
        );
        jTable_paciente.setModel(modeloTabla);
    }

    /**
     * Carga los clientes desde la base de datos en la tabla.
     */
    private void cargarClientesEnTabla() {
        modeloTabla.setRowCount(0); // Limpiar la tabla
        ClienteLogica clienteLogica = new ClienteLogica();
        List<Cliente> clientes = clienteLogica.obtenerClientes();

        for (Cliente cliente : clientes) {
            modeloTabla.addRow(new Object[]{
                    cliente.getIdUsuario(),
                    cliente.getNombre(),
                    cliente.getDni(),
                    cliente.getDireccion(),
                    cliente.getTelefono(),
                    cliente.getTieneMedidor(),
                    cliente.getEstadoServicio(),
                    cliente.getFechaInstalacion()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jTextField_direccion = new javax.swing.JTextField();
        jTextField_dni = new javax.swing.JTextField();
        jTextField_telefono = new javax.swing.JTextField();
        jRadioButton_medidor_option_si = new javax.swing.JRadioButton();
        jRadioButton_medidor_option_no = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton_estadoServicio_option_activo = new javax.swing.JRadioButton();
        jRadioButton_estadoServicio_option_suspendido = new javax.swing.JRadioButton();
        jDateChooser_fechaInstalacion = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_registrar = new javax.swing.JButton();
        jButton_modificar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnAtrasV3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_paciente = new javax.swing.JTable();
        jButton_eliminar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setText("FactuTrack");

        jLabel2.setText("Nombre:");

        jLabel3.setText("DNI:");

        jLabel4.setText("Dirección:");

        jLabel5.setText("Telefono:");

        jLabel6.setText("Medidor:");

        jLabel7.setText("Fecha de instalación:");

        jTextField_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreActionPerformed(evt);
            }
        });

        jRadioButton_medidor_option_si.setText("Sí");

        jRadioButton_medidor_option_no.setText("No");

        jLabel9.setText("Estado servicio:");

        jRadioButton_estadoServicio_option_activo.setText("Activo");

        jRadioButton_estadoServicio_option_suspendido.setText("Suspendido");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_direccion)
                    .addComponent(jTextField_nombre)
                    .addComponent(jTextField_dni)
                    .addComponent(jTextField_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_medidor_option_si)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_medidor_option_no))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton_estadoServicio_option_activo)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_estadoServicio_option_suspendido))
                    .addComponent(jDateChooser_fechaInstalacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_direccion, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jRadioButton_medidor_option_si)
                    .addComponent(jRadioButton_medidor_option_no))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jRadioButton_estadoServicio_option_activo)
                    .addComponent(jRadioButton_estadoServicio_option_suspendido))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jDateChooser_fechaInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Registrar nuevo usuario");

        jScrollPane1.setViewportView(jTable1);

        jButton_registrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_registrar.setText("Registrar");
        jButton_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registrarActionPerformed(evt);
            }
        });

        jButton_modificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_modificar.setText("Modificar");
        jButton_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_modificarActionPerformed(evt);
            }
        });

        btnAtrasV3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAtrasV3.setText("Atras");
        btnAtrasV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasV3ActionPerformed(evt);
            }
        });

        jTable_paciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_pacienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_paciente);

        jButton_eliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel11.setText("Lista Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(175, 175, 175)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton_registrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(jButton_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAtrasV3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAtrasV3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jTextField_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreActionPerformed

    /**
     * Acción del botón "Atrás".
     *
     * @param evt Evento del botón.
     */
    private void btnAtrasV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasV3ActionPerformed
        // TODO add your handling code here:
        v2.setVisible(true); // Volver al Dashboard
        this.setVisible(false); // Ocultar esta ventana
    }//GEN-LAST:event_btnAtrasV3ActionPerformed

    /**
     * Acción del botón "Registrar".
     *
     * @param evt Evento del botón.
     */
    private void jButton_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registrarActionPerformed
        // Capturar datos del formulario
        String nombre = jTextField_nombre.getText().trim();
        String dni = jTextField_dni.getText().trim();
        String direccion = jTextField_direccion.getText().trim();
        String telefono = jTextField_telefono.getText().trim();
        String fechaInstalacion = obtenerFechaInstalacion();
        String tieneMedidor = jRadioButton_medidor_option_si.isSelected() ? "Sí" : "No";
        String estadoServicio = jRadioButton_estadoServicio_option_activo.isSelected() ? "Activo" : "Suspendido";

        if (nombre.isEmpty() || dni.isEmpty() || fechaInstalacion == null) {
            JOptionPane.showMessageDialog(this, "Por favor complete los campos obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Cliente cliente = new Cliente();
        cliente.setNombre(nombre);
        cliente.setDni(dni);
        cliente.setDireccion(direccion);
        cliente.setTelefono(telefono);
        cliente.setFechaInstalacion(fechaInstalacion);
        cliente.setTieneMedidor(tieneMedidor);
        cliente.setEstadoServicio(estadoServicio);

        ClienteLogica clienteLogica = new ClienteLogica();
        if (clienteLogica.agregarCliente(cliente)) {
            JOptionPane.showMessageDialog(this, "Cliente registrado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
            cargarClientesEnTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar el cliente.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_registrarActionPerformed

    /**
     * Acción del botón "Modificar".
     *
     * @param evt Evento del botón.
     */
    private void jButton_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_modificarActionPerformed
        int filaSeleccionada = jTable_paciente.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente de la tabla.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idCliente = (int) modeloTabla.getValueAt(filaSeleccionada, 0);

        // Capturar datos del formulario
        String nombre = jTextField_nombre.getText().trim();
        String dni = jTextField_dni.getText().trim();
        String direccion = jTextField_direccion.getText().trim();
        String telefono = jTextField_telefono.getText().trim();
        String fechaInstalacion = obtenerFechaInstalacion();
        String tieneMedidor = jRadioButton_medidor_option_si.isSelected() ? "Sí" : "No";
        String estadoServicio = jRadioButton_estadoServicio_option_activo.isSelected() ? "Activo" : "Suspendido";

        if (nombre.isEmpty() || dni.isEmpty() || fechaInstalacion == null) {
            JOptionPane.showMessageDialog(this, "Por favor complete los campos obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Cliente cliente = new Cliente();
        cliente.setIdUsuario(idCliente);
        cliente.setNombre(nombre);
        cliente.setDni(dni);
        cliente.setDireccion(direccion);
        cliente.setTelefono(telefono);
        cliente.setFechaInstalacion(fechaInstalacion);
        cliente.setTieneMedidor(tieneMedidor);
        cliente.setEstadoServicio(estadoServicio);

        ClienteLogica clienteLogica = new ClienteLogica();
        if (clienteLogica.actualizarCliente(cliente)) {
            JOptionPane.showMessageDialog(this, "Cliente modificado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            limpiarCampos();
            cargarClientesEnTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Error al modificar el cliente.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_modificarActionPerformed

    private void jTable_pacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_pacienteMouseClicked
        // TODO add your handling code here:
        // Obtener la fila seleccionada en la tabla
        int filaSeleccionada = jTable_paciente.getSelectedRow();

        if (filaSeleccionada != -1) {
            // Cargar los datos de la fila seleccionada en los campos del formulario
            jTextField_nombre.setText((String) modeloTabla.getValueAt(filaSeleccionada, 1));
            jTextField_dni.setText((String) modeloTabla.getValueAt(filaSeleccionada, 2));
            jTextField_direccion.setText((String) modeloTabla.getValueAt(filaSeleccionada, 3));
            jTextField_telefono.setText((String) modeloTabla.getValueAt(filaSeleccionada, 4));

            // Configurar el estado del medidor basado en el valor de la tabla
            String tieneMedidor = (String) modeloTabla.getValueAt(filaSeleccionada, 5);
            jRadioButton_medidor_option_si.setSelected(tieneMedidor.equals("Sí"));
            jRadioButton_medidor_option_no.setSelected(tieneMedidor.equals("No"));

            // Configurar el estado del servicio basado en el valor de la tabla
            String estadoServicio = (String) modeloTabla.getValueAt(filaSeleccionada, 6);
            jRadioButton_estadoServicio_option_activo.setSelected(estadoServicio.equals("Activo"));
            jRadioButton_estadoServicio_option_suspendido.setSelected(estadoServicio.equals("Suspendido"));

            // Configurar la fecha de instalación en el JDateChooser
            try {
                String fechaInstalacion = (String) modeloTabla.getValueAt(filaSeleccionada, 7);
                Date fecha = new SimpleDateFormat("yyyy-MM-dd").parse(fechaInstalacion);
                jDateChooser_fechaInstalacion.setDate(fecha);
            } catch (Exception e) {
                jDateChooser_fechaInstalacion.setDate(null); // Si ocurre un error, dejar el campo vacío
            }
        }
    }//GEN-LAST:event_jTable_pacienteMouseClicked

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        // TODO add your handling code here:
        // Verificar si se ha seleccionado una fila
        int filaSeleccionada = jTable_paciente.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente de la tabla para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtener el ID del cliente seleccionado
        int idCliente = (int) modeloTabla.getValueAt(filaSeleccionada, 0);

        // Confirmar la eliminación
        int confirmacion = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de que desea eliminar este cliente?", 
            "Confirmación", 
            JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            // Llamar a la lógica para eliminar el cliente
            ClienteLogica clienteLogica = new ClienteLogica();
            if (clienteLogica.eliminarCliente(idCliente)) {
                JOptionPane.showMessageDialog(this, "Cliente eliminado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                cargarClientesEnTabla(); // Recargar la tabla después de eliminar
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar el cliente. Verifique la conexión o los datos.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton_eliminarActionPerformed

    /**
     * Acción al seleccionar una fila de la tabla.
     */
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtrasV3;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JButton jButton_modificar;
    private javax.swing.JButton jButton_registrar;
    private com.toedter.calendar.JDateChooser jDateChooser_fechaInstalacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_estadoServicio_option_activo;
    private javax.swing.JRadioButton jRadioButton_estadoServicio_option_suspendido;
    private javax.swing.JRadioButton jRadioButton_medidor_option_no;
    private javax.swing.JRadioButton jRadioButton_medidor_option_si;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_paciente;
    private javax.swing.JTextField jTextField_direccion;
    private javax.swing.JTextField jTextField_dni;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_telefono;
    // End of variables declaration//GEN-END:variables
}
